### ISSUE TITLE
Lots of artifacts in boosted depth map?

### ISSUE THREAD

**Issue by oscarqht** [compphoto/BoostYourOwnDepth#6]
Hi. Thanks for sharing this great work! I'm having issue generating clean and detail-rich depth map like you showcase in the project. I'm using MiDaS `dpt_swin2_tiny_256` and `dpt_beit_large_512` to generate the low-res & high-res depth map, then feed them into the colab notebook. But the boosted depth map is filled with artifacts (please see the screenshots below). Any idea what might be the issue? Thank you :)

<img width="1455" alt="Snipaste_2023-03-07_17-58-06" src="https://user-images.githubusercontent.com/165961/223389360-c27a56db-4517-4451-88d0-06e09559cf1f.png">
<img width="1454" alt="Snipaste_2023-03-07_17-59-26" src="https://user-images.githubusercontent.com/165961/223389380-5a323edc-c77b-4eee-baad-19e53d7f3479.png">

**Comment by sebastian-dille** [comment]
Hi @m0o0scar, this is interesting. To my knowledge, we never came across these types of artifacts that you see on the heads and chest region. These also look more like banding problems to me and not like actual depth errors.

When you look at the region around the right arm in the high-res version of the first picture, you see a dark gap underneath and a somewhat blurry background to the right. These are the kind of depth artifacts that I am aware of and that are usually created by the estimation network due to its receptive field limit. But the merging network seems to deal with those problems reasonably well.

The banding however is new to me and I don't know right now where it's coming from. Would you mind sending me one of the RGB inputs, so that I can do some testing?

**Comment by oscarqht** [comment]
Hi @sebastian-dille , thanks for the reply. Sure I'm happy to provide the original RGB images, you may download them from the links below:
https://drive.google.com/file/d/1Jsv-p_HwH7TvlsPPrxP-k3T8rmVN1Oi_/view?usp=sharing
https://drive.google.com/file/d/1Jbt_zfefL8B18zOVOZfqU6qQIej6uJ9i/view?usp=sharing

**Comment by oscarqht** [comment]
May I confirm that using MiDaS `dpt_swin2_tiny_256` and `dpt_beit_large_512` to generate the low-res & high-res depth map respectively is correct? @sebastian-dille

**Comment by sebastian-dille** [comment]
Hi @m0o0scar thanks for sharing the images. I'll see if I can find where this is coming from.

Regarding the MiDaS version, most images that we've generated are either from version v2.1 (ConvNet based) for both low- and high-res, or using the hybrid DPT architecture (dpt_hybrid-midas-501f0c75 from the original repo) for low-res and again v2.1 for high-res.
However, there isn't really a "right" or "wrong" here. The merging network should be able to deal with all kinds of depth maps, as long as they're not sparse. The question is just how much improvement you can get.

**Comment by sebastian-dille** [comment]
Hi @m0o0scar, just to clarify:
Have you run the merging based on colorized inputs?
I've noticed that the MiDaS implementation reduces the output bit depth to 8 bit for colorized results due to the colormap.
If that's your pipeline, try getting the grayscale results (there's a --grayscale option for MiDaS) and then run our approach on those. The grayscale maps are 16 bit and shouldn't produce these banding artifacts.

**Comment by oscarqht** [comment]
Hi @sebastian-dille, yes indeed it was based on colorized inputs. I added the `--grayscale` option as you suggested and it's working very good now! All those artifacts are gone! Thanks a lot!

**Comment by suptimq** [comment]
Hi @m0o0scar , I am wondering if you could share the steps (or the code) to generate the low-res & high-res depth map using MiDaS `dpt_swin2_tiny_256` and `dpt_beit_large_512`.
